import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const inter = Inter({ subsets: ['latin'] })


export default function RootLayout({ children }) {
  return (
    <html style={{scrollbarColor: "#A61C1C rgba(216, 215, 215, 0.438)" , scrollbarWidth: "thin"}}  lang="en">
      <body className={`${inter.className} antialiased`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
